### ISSUE TITLE
Dashboard can't see the device 

### ISSUE THREAD

**Issue by cycxtIT** [efxtv/L3MON#10]
I generated an apk file in the computer, I sent it to my mobile phone and opened the app, but the dashboard of the computer did not show the device. I refreshed the page and it's the same.So,how to fix it?

**Comment by BilawalSh** [comment]
it required port forwarding

**Comment by maxc1234kali** [comment]
is not working and it doesn't even have a server include it when i clone it.?

**Comment by efxtv** [comment]
Working fine. Get in touch t.me/efxtv
