### ISSUE TITLE
Lemon apk building error 🥺🥺

### ISSUE THREAD

**Issue by only-foryou** [efxtv/L3MON#13]
After starting lemon server on my termux then I can login successfully on lemon server now if I click build apk I got 👉 👇👇👇👈
ERROR Build Failed - Build Command Failed - Command failed: proot java -jar "/data/data/com.termux/files/usr/share/lemon/app/factory/apktool.jar" b "/data/data/com.termux/files/usr/share/lemon/app/factory/decompiled" -o "/data/data/com.termux/files/usr/share/lemon/assets/webpublic/build.apk"
proot error: '/data/data/com.termux/files/usr/share/jdk8/bin/java' is a 64-bit program whereas this version of proot handles 32-bit programs only                                                                 proot info: vpid 1: terminated with signal 11
👉👉👉👇👇👇👈👈👈
This error... please help me..😭😭I also install java
![Screenshot_2023-08-04-05-37-26-881_com android chrome](https://github.com/efxtv/L3MON/assets/137401490/db0c2347-dd7d-4a08-ad05-83638139d440)
![Screenshot_2023-08-04-05-33-21-560_com termux](https://github.com/efxtv/L3MON/assets/137401490/b02d1577-98df-4f1e-8d41-f47bb56ff5d7)

**Comment by rammos92** [comment]
install java 8

**Comment by efxtv** [comment]
this is not our repository
