### ISSUE TITLE
I can't get the latest release of l3mon

### ISSUE THREAD

**Issue by TheNerdOne213** [efxtv/L3MON#14]
When I click on the telegram link it says user not found or something.. 
Can you send me a working link for l3mon please?
I would really appreciate it.. and thanks for your hard work 😊👍

**Comment by TheNerdOne213** [comment]
I'm so sorry.. I found the working link of your telegram channel here: https://github.com/efxtv/L3MON/issues/5
You can close this issue now..
So sorry again 😞🙏

**Comment by efxtv** [comment]
Please get in touch on telegram to get a paid version of l3mon with 24*7 support and assistance. visit [here](https://t.me/erorfix_tv)
