### ISSUE TITLE
Can't access login page

### ISSUE THREAD

**Issue by LuckyFishGeek** [efxtv/L3MON#6]
![Snipaste_2023-04-07_09-20-50](https://user-images.githubusercontent.com/29472751/230521316-2ef2a07e-dbe2-436b-8785-21a6af53b4a1.png)
![Snipaste_2023-04-07_09-21-41](https://user-images.githubusercontent.com/29472751/230521348-3a7b2a5e-7d20-493c-947b-843c21b2e5be.png)

**Comment by loser-arch** [comment]
same problem here
bro you fix this problem ?
if you fix this problem can you tell me please i need help

**Comment by efxtv** [comment]
Please get in touch https://t.me/efxtv
